hats-finance/hats

package.json, src/components/WalletInfo/WalletInfo.scss, src/components/WalletInfo/WalletInfo.tsx, src/hooks/useENS.js, yarn.lock
=> feat: add ens name and avatar support

app.json
to build new review apps with default build packs.
=> Added app.json

src/App.tsx, src/data/vaults.tsx
This is a temporary solution until the protected token will be manifested in the subgraph.
=> Use protected token for UMA to get the price

.github/workflows/codeql-analysis.yml
=> Add codeql security analysis

static.json
=> Support ipfs

src/components/Airdrop/components/Airdrop/Airdrop.tsx, src/components/Honeypots.tsx, src/components/Vault/Severities/Severity.scss, src/components/Vault/Severities/Severity.tsx, src/components/Vault/Vault.tsx, src/components/Vulnerability/TermsAndProcess/TermsAndProcess.tsx, src/components/Vulnerability/TermsAndProcess/index.scss, src/styles/Vault/Vault.scss, src/styles/constants.scss, src/types/types.ts, src/utils.ts
- temporary disable token airdrop.
- some minor updates
=> Logic for gamification vault

package.json, src/actions/contractsActions.ts, src/components/Airdrop/components/Airdrop/Airdrop.tsx, src/components/Airdrop/components/NFTAirdop/NFTAirdrop.tsx, src/components/Airdrop/utils.ts, src/components/DepositWithdraw/DepositWithdraw.tsx, src/components/Honeypots.tsx, src/components/Vault/Vault.tsx, src/components/VaultEditor/VaultEditor.tsx, src/components/Vulnerability/ProjectSelect.tsx, src/hooks/useVaults.ts, src/settings.ts, src/utils.ts
- resolves: #182
- Eliminate token airdrop warnings due to temporary disabling it
- Eliminate redundant check of `Project-metadata` and `project-metadata` - it's already fixed now in `useVaults`
- Update dApp `package.json` version
- use `pollInterval` using a constant in `settings.ts`
=> General updates

src/components/DepositWithdraw/DepositWithdraw.tsx, src/components/Honeypots.tsx, src/components/Vault/Severities/Severity.tsx, src/components/Vault/Vault.tsx, src/components/VaultEditor/VaultEditor.tsx, src/components/VaultEditor/VaultReview.tsx, src/components/Vulnerability/ProjectSelect.tsx, src/components/Vulnerability/TermsAndProcess/TermsAndProcess.tsx, src/hooks/useVaults.ts, src/reducers/data.ts, src/types/types.ts, src/utils.ts
=> v1.1 bug fixes

src/components/VaultEditor/VaultReview.tsx
=> fix vault edirtor review bug

src/actions/contractsActions.ts, src/components/DepositWithdraw/DepositWithdraw.tsx, src/components/Honeypots.tsx, src/components/Notifications/NotificationProvider.tsx, src/components/Vault/Severities/Severity.tsx, src/components/Vault/Vault.tsx, src/components/VaultEditor/VaultEditor.tsx, src/components/Vulnerability/TermsAndProcess/TermsAndProcess.tsx, src/config/apollo.ts, src/config/ethers.ts, src/constants/constants.ts, src/graphql/uniswap.ts, src/hooks/contractHooks.ts, src/hooks/useVaults.ts, src/index.tsx, src/reducers/data.ts, src/settings.ts, src/types/types.ts
Ability to show subgraph and provider and make actions on both rinkeby and mainnet
receive prices from Uniswap v3 TWAP 
show errors from usedapp properly -> with timeout
=> multichain support

src/components/Vulnerability/Submit/Submit.tsx, src/components/Vulnerability/Submit/components/SubmitReview/SubmitReview.tsx, src/components/Vulnerability/Submit/components/SubmitSuccess/SubmitSuccess.tsx, src/constants/constants.ts, src/settings.ts
utilize new bot chainId ability so only one bot is needed 
fallback to default bot
=> add chainId to bot call + default bot fallback

package.json, src/App.tsx, src/components/Honeypots.tsx, src/components/Vault/Vault.tsx, src/components/Vault/VaultAction.tsx, src/components/Vault/VaultExpanded.tsx, src/styles/Vault/Vault.scss, yarn.lock
Fix markdown style as well
resolves #229
=> vaults routing

src/components/Honeypots.tsx, src/components/Vault/Severities/Severity.tsx, src/components/Vault/Vault.tsx, src/components/Vault/VaultExpanded.tsx, src/components/VaultEditor/VaultEditor.tsx, src/hooks/useVaults.ts, src/languages/en.json, src/types/types.ts
=> Vaults type support

package.json, src/components/Vault/VaultExpanded.tsx, src/components/Vulnerability/ProjectSelect/ProjectSelect.tsx, src/components/Vulnerability/Submit/Submit.tsx, src/components/Vulnerability/Submit/components/SubmitReview/SubmitReview.tsx, src/components/Vulnerability/Submit/components/SubmitSuccess/SubmitSuccess.tsx, src/components/Vulnerability/VulnerabilityAccordion.tsx, src/components/Vulnerability/types.ts, src/hooks/useRewardsToken.ts, src/utils.ts
=> Add master address for telegram bot payload

src/components/Notifications/NotificationProvider.tsx, src/components/Shared/Countdown/Countdown.tsx, src/hooks/useVaults.tsx, src/settings.ts
- Show unsupported network error
- Update vaults after a transaction
- Fix wrong zeros padding in countdown
=> General fixes

src/components/VaultEditor/VaultDetails.tsx, src/languages/en.json
=> add vault type field

src/components/NFTMedia.tsx, src/components/Vault/Severities/Severities.tsx, src/components/Vault/Severities/Severity.scss, src/components/Vault/Severities/Severity.tsx, src/components/Vulnerability/TermsAndProcess/components/Award/Award.tsx, src/components/Vulnerability/TermsAndProcess/index.scss, src/constants/constants.ts, src/styles/Vault/Vault.scss, src/styles/constants.scss, src/utils.ts
resolves: #132 
- Also show NFT in case there is no file extension - neater code
=> Severities colors & NFT media display updates

src/components/AirdropMachine/components/Redeem/components/NFTAirdrop/NFTAirdrop.tsx, src/components/AirdropMachine/components/Redeem/components/NFTAirdrop/index.scss, src/components/NFTCard/index.scss, src/components/RedeemNftSuccess/index.scss, src/languages/en.json
resolves: #330
Also resolves issue where nft cards are in different hight due to long vaults names
=> Resolve ticket #330

src/hooks/contractHooks.ts, src/languages/en.json, src/layout/BasicLayout/BasicLayout.tsx, src/pages/HoneypotsPage/DepositWithdraw/Assets/Assets.tsx, src/pages/HoneypotsPage/DepositWithdraw/Assets/DepositAmount.tsx, src/pages/HoneypotsPage/DepositWithdraw/DepositWithdraw.tsx, src/pages/HoneypotsPage/DepositWithdraw/utils.ts
Now in V1 vaults, we are converting shares to tokens. The user inputs the value in TOKENS and that value is converted to shares in order to call the SC.
=> Now using shares and calculating value in tokens for v1 vaults

src/components/Keystore/KeyManager/KeyManager.tsx, src/components/Keystore/UnlockKeystoreModal/UnlockKeystoreModal.tsx, src/pages/VulnerabilityFormPage/VulnerabilityFormPage.tsx
- Fixed issue on refreshing/connecting wallet while you were creating a vulnerability submission.
- Now unlock keystore modal is closable on vault editor.
=> Fixes on main

src/components/Vault/Vault.tsx, src/components/Vault/VaultExpanded/ContractsCovered/ContractsCovered.tsx, src/components/Vault/VaultExpanded/Severities/Severity.tsx, src/components/WalletButton/styles.ts
- Minor UI bug with Wallet Button on mobile screen
- Bug with network tooltip on vaults
- Bug with the redirection link on contracts covered: now redirecting to etherscan
=> Bug fixes :D Merry Christmas 

src/pages/VulnerabilityFormPage/encrypt.ts
we will merge this once we update the bot
=> remove replace from ipfs cid calculation

packages/web/src/components/Keystore/components/KeystoreDashboard/CreateKey/CreateKey.tsx
Release Notes:
- New Feature: `CreateKey` component now handles errors and adds a new key to `storedKeys`.
> "A new key is born, with no errors to mourn. Our code is now reborn, with fewer bugs to scorn."
=> some improvements based on review

packages/shared/src/severities.ts, packages/web/src/pages/VaultEditor/VaultEditorFormPage/SetupSteps/VaultDetailsForm/VaultDetailsForm.tsx, packages/web/src/pages/VaultEditor/VaultEditorFormPage/SetupSteps/VulnerabilitySeveritiesList/VulnerabilitySeverityForm/VulnerabilitySeverityForm.tsx
- New Feature: Added a new severity level for high severity vulnerabilities and updated the descriptions of existing levels in `packages/shared/src/severities.ts`. It also includes submission guidelines and limitations for each severity level.
- New Feature: Added functionality to change vulnerability templates and increase the number of rows in a textarea in `packages/web/src/pages`.
> "New severities, templates too,
> Better security, thanks to you!"
=> Added vulnerabilities template for Audits

packages/shared/src/severities.ts, packages/web/src/utils.ts
- New Feature: Added support for an additional IPFS URI format and updated IPFS URLs in `severities.ts`.
- Refactor: Changes to `ipfsTransformUri` function in `utils.ts`.
> "IPFS URLs, oh how they change,
> With new formats, we must arrange.
> But fear not, our code is sound,
> Bugs and vulnerabilities won't be found."
=> Hotfix: ipfs parser and template

packages/web/src/pages/HoneypotsPage/HoneypotsPage.tsx, packages/web/src/pages/VaultEditor/vaultEditorService.ts, packages/web/src/pages/VulnerabilityFormPage/VulnerabilityFormPage.tsx
Refactored the way vaults are grouped by type in the `vaultsByGroup` object for improved readability and maintainability. The URL of an API endpoint was changed from `/broadcast-message` to `/messages/broadcast-message`. Additionally, changes were made to function calls that could impact the behavior of the code.
> A refactor here, a bug fix there,  
> Changes made with utmost care.  
> Readability and maintainability improved,  
> Code behavior thoroughly reviewed.  
> Celebrate this PR with a cheer,  
> For better code is finally here!
=> [HOTFIX] Hotfixes with payout feature

packages/web/public/index.html
Chore: Update Google Analytics tracking code and minor formatting changes in `packages/web/public/index.html`.
> "Tracking our users with care, 
> Google Analytics now aware. 
> Minor tweaks to make it right, 
> Our website shines ever so bright."
=> New GA4 implementation

packages/web/src/pages/SubmissionFormPage/FormSteps/SubmissionDescriptions/utils.ts, packages/web/src/pages/SubmissionFormPage/submissionsService.api.ts
Release Notes:
- New Feature: Added `getGithubIssueDescription` function to `utils.ts` to generate a formatted string for the GitHub issue description.
- Bug fix: Modified `submitVulnerabilitySubmission` function in `submissionsService.api.ts` to use `getGithubIssueDescription` instead of `getIssueDescription`.
> "A new function is born, to make our code less forlorn. With better GitHub descriptions, we'll have fewer subscriptions. Bugs fixed, features added, our codebase is never stagnant."
=> [Fixes] Improved github issue description generation

packages/web/src/pages/CommitteeTools/PayoutsTool/PayoutStatusPage/useSignPayout.ts
- **Logic/Security/Performance:** The `useSignPayout` module has been updated to replace the previous signing method with a new one, using `safeSdk.signTypedData()`. This change may have implications for security and performance, and the new `useSigner()` hook should be reviewed for correctness.
> 🎉 Oh, what changes this PR brings!  
> 🤖 A bot's review of code with wings.  
> 🔍 Logic, security, and performance too,  
> 🚀 All improved with changes anew.  
> 💻 Let's celebrate this code's rebirth,  
> 🎊 And merge it into our codebase on Earth!
=> [FIX] Now using safe sign method 

packages/shared/package.json, packages/shared/src/utils/gnosis.utils.ts, packages/shared/src/utils/vaults.utils.ts, packages/web/src/languages/en.json, packages/web/src/pages/CommitteeTools/PayoutsTool/PayoutFormPage/PayoutFormPage.tsx, packages/web/src/pages/CommitteeTools/PayoutsTool/PayoutStatusPage/PayoutStatusPage.tsx, packages/web/src/pages/CommitteeTools/PayoutsTool/PayoutsListPage/PayoutsListPage.tsx, packages/web/src/pages/CommitteeTools/PayoutsTool/payoutsService.api.ts, packages/web/src/pages/CommitteeTools/PayoutsTool/payoutsService.hooks.ts
Release Notes:
- New Feature: Added two new functions to retrieve information about vaults from a subgraph in `vaults.utils.ts`.
- Bug fix: Improved error handling and added refetch functionality in `PayoutFormPage.tsx` and `PayoutStatusPage.tsx`.
- Refactor: Modified function signatures and API endpoints in `payoutsService.api.ts` and `payoutsService.hooks.ts`.
- Style: Updated import statements in `PayoutStatusPage.tsx` and `PayoutsListPage.tsx`.
> "Code changes abound,  
> Bugs fixed and features found.  
> With each review we grow,  
> And make our codebase glow."
=> [Improvement] Permission to gov on payouts and flow improvements

packages/web/src/pages/SubmissionFormPage/FormSteps/SubmissionDescriptions/utils.ts
Asked by community :)
@GalloDaSballo
@Rotcivegaf
Release Notes:
- New Feature: Added "Beneficiary" field to submission text in `getAuditSubmissionTexts` function.
> "A new field has arrived,
> Beneficiary, now we thrive.
> With added security in mind,
> Our code is safe and sound, we find."
=> [HOTFIX] Now encrypting beneficiary

packages/web/src/components/FormControls/FormMDEditor/styles.ts, packages/web/src/pages/SubmissionFormPage/FormSteps/SubmissionDescriptions/SubmissionDescriptions.tsx, packages/web/src/pages/SubmissionFormPage/FormSteps/SubmissionDescriptions/utils.ts, packages/web/src/pages/SubmissionFormPage/store.ts
Release Notes:
- New Feature: A submission description template has been added to the form.
- Refactor: Minor changes to code style and console.log statements.
> "A template for submissions, now in store,
> Makes filling out forms a little less a chore.
> With font-size gone and logs removed,
> Code quality is surely improved."
=> [Feature] Added submission description template

packages/web/src/application/Root.tsx, packages/web/src/components/Header/Header.tsx, packages/web/src/components/Sidebar/NavLinks/NavLinks.tsx, packages/web/src/components/Vault/VaultActions/VaultActions.tsx, packages/web/src/components/VaultCard/VaultCard.tsx, packages/web/src/config/encryptedStorage.ts, packages/web/src/navigation/routes.tsx, packages/web/src/pages/Honeypots/VaultDetailsPage/VaultDetailsPage.tsx, packages/web/src/pages/Honeypots/router.tsx, packages/web/src/pages/HoneypotsPage/HoneypotsPage.tsx
Release Notes:
- Refactor: Moved the `<Seo isMainPage />` component inside the `<RouterToUse>` component in `Root.tsx`.
- Refactor: Modified conditions for determining page title in `Header.tsx`, removing `${RoutePaths.vaults}` prefix.
- Refactor: Modified `to` prop of two `StyledNavLink` components in `NavLinks.tsx`, removing `${RoutePaths.vaults}/` prefix.
- Refactor: Updated import statements, reordering of imports, and modified `onClick` event handler in `VaultActions.tsx`.
- Refactor: Updated logic for constructing `mainRoute` variable and values for displaying rewards in `VaultCard.tsx`.
- Refactor: Generated a cryptographically secure random key for encryption and initialized `encryptedStorage` with `EncryptStorage` class in `encryptedStorage.ts`.
- Refactor: Modified routing paths …
=> [Hotfixes] Fixes on new app version

packages/web/package.json, packages/web/src/components/VaultCard/VaultCard.tsx, packages/web/src/pages/Honeypots/VaultDetailsPage/VaultDetailsPage.tsx
Bug fix: Fixed an issue where routes were not properly constructed and navigated in the code. Added a leading slash ("/") to the `mainRoute` variable and the `navigate` function calls.
> "Routes fixed, bugs no more,
> With slashes leading, we'll explore.
> Code now navigates with grace,
> Unintended issues we erase."
=> [Hotfix] Fixed issues on routes

.github/workflows/IPFS_deploy.yml
Release Notes:
- Chore: Updated workflow name, Node.js version to 18.x, and added an environment variable for `REACT_APP_ENCRYPTED_STORAGE_KEY` in `.github/workflows/IPFS_deploy.yml`.
> "A new workflow emerges,
> Node.js 18.x takes the stage.
> With encrypted storage key,
> Our deployment soars with glee."
=> Deploy to ipfs update action

packages/web/src/components/VaultCard/oneLinerFallback.ts
Release Notes:
- New Feature: Added a new entry for the Swapr protocol in `oneLinerFallback.ts` file.
> "A new entry for Swapr, a protocol so fine,
> Enhancing our code, it's a feature divine.
> With data structure changed, behavior may shift,
> Let's review and ensure it's a positive lift."
=> [FIX] Added Swapr oneliner

packages/web/src/components/Sidebar/NavLinks/styles.ts, packages/web/src/components/Sidebar/styles.ts, packages/web/src/components/VaultCard/VaultCard.tsx, packages/web/src/components/VaultCard/styles.ts, packages/web/src/hooks/vaults/useVaults.tsx, packages/web/src/languages/en.json, packages/web/src/pages/Honeypots/VaultsPage/AuditVaultsPage.tsx, packages/web/src/pages/Honeypots/VaultsPage/hooks.ts
Release Notes:
- New Feature: Added UI improvements and responsiveness to the sidebar components.
- Refactor: Modified logic and styling of the `VaultCard` component.
- Refactor: Updated the `useVaults` hook by commenting out a block of code.
- New Feature: Added a new hook, modified existing hooks, and fetched/displayed additional data in the `AuditVaultsPage` component.
> "Code changes dance,
> UI shines with elegance.
> Bugs fixed, features bloom,
> A release that brings joy to the room!"
=> [Feature] Now showing old Audits data & UI improvements

packages/web/src/pages/Submissions/SubmissionFormPage/FormSteps/SubmissionDescriptions/SubmissionDescriptions.tsx, packages/web/src/pages/Submissions/SubmissionFormPage/encrypt.ts
```
- Added validation for encryption keys in the submission form. The system now checks if the provided keys are valid before proceeding with encryption.
- Updated `encryptWithKeys` function to skip invalid keys during the encryption process.
- Enhanced error handling: If `encryptWithKeys` returns a falsy value, an alert is displayed to the user.
> 🎉 With keys checked and errors trapped, 🛡️
> Our data's journey is securely mapped. 🗺️
> No more worries, no more fears, 🚫
> For our code now steers clear of invalid keys' snares! 🔑🎊
```
=> Skip invalid keys
